# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Africa/Cairo

# jekyll-seo-tag settings
title: Malak's Blog  # the main title
tagline: Junior AI Student  # the sub-title

description: >-
  Computer Science student passionate about artificial intelligence, competitive programming, and open-source contributions.

# Fill in the protocol & hostname for your site.
url: "https://MalakMohamed.github.io"  # replace with your actual site URL

github:
  username: MalakMohameed  # replace with your GitHub username
linkedin: "https://www.linkedin.com/in/malak-mohamed-81a343212/"  # Make sure LinkedIn URL is filled out

social:
  name: Malak Mohamed  # Your name
  email: malakmohamedabdelrazeq04@gmail.com  # Your email address
  links:
    - https://github.com/MalakMohameed  # GitHub profile URL
    - https://www.linkedin.com/in/malak-mohamed-81a343212/  # LinkedIn profile URL

google_site_verification: your-verification-code  # Use your actual Google Site Verification code here

# jekyll-seo-tag settings end

google_analytics:
  id: G-XXXXXXX  # Replace with your actual Google Analytics ID

# Prefer color scheme setting (empty will follow system preference)
theme_mode:  # light or dark or empty for system preference

# The CDN endpoint for images (optional)
img_cdn: "" 

# The avatar on sidebar (use a valid URL to your avatar image)
avatar: https://your-avatar-image-url.com  # Replace with your actual avatar URL

# Social preview image for SEO (optional)
social_preview_image: ""  # Optional, you can provide a URL for your SEO image

# Table of contents (TOC) setting
toc: true

comments:
  active: false  # Disabled by default; change to true to enable
  disqus:
    shortname: ""  # Your Disqus shortname, leave empty to disable
  utterances:
    repo: ""  # GitHub repository for comments, leave empty to disable
    issue_term: "title"  # The term to associate with issues
  giscus:
    repo: ""  # GitHub repository for Giscus comments
    repo_id: ""
    category: ""
    category_id: ""
    mapping: "pathname"
    lang: "en"

pwa:
  enabled: true  # Enable PWA feature (installable)
  cache:
    enabled: true  # Enable offline cache
    deny_paths: []  # No specific paths excluded from cache

paginate: 10  # Number of posts per page

# Base URL of your site
baseurl: ""  # Leave empty for default URL

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""  # Applies to all files in the project
      type: posts
    values:
      layout: post
      comments: true  # Enable comments on posts
      toc: true  # Enable TOC for posts
      permalink: /posts/:title/  # Post permalink structure
  - scope:
      path: _drafts  # Draft posts don't have comments
    values:
      comments: false
  - scope:
      path: ""
      type: tabs  # For tabbed layouts
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist  # Cache for PWA assets
    values:
      swcache: true

sass:
  style: compressed  # Compress CSS output

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]  # Ignore compression in development

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
