# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Africa/Cairo

# jekyll-seo-tag settings
title: Malak's Blog  # the main title
tagline: Junior AI Student  # the sub-title

description: >-
  Computer Science student passionate about artificial intelligence, competitive programming, and open-source contributions.

# Fill in the protocol & hostname for your site.
url: "https://MalakMohamed.github.io"  # replace with your actual site URL

github:
  username: MalakMohameed  # replace with your GitHub username
linkedin:


social:
  name: Malak Mohamed  # Change to your name
  email: malakmohamedabdelrazeq04@gmail.com  # Change to your email address
  links:
    - https:https://github.com/MalakMohameed  # replace with your GitHub profile URL
    - https:https://www.linkedin.com/in/malak-mohamed-81a343212/  # replace with your LinkedIn URL

google_site_verification: your-verification-code

# jekyll-seo-tag settings end

google_analytics:
  id: G-XXXXXXX  # Replace with your Google Analytics ID

# Prefer color scheme setting
theme_mode:  # light or dark or empty for system preference

# The CDN endpoint for images
img_cdn: ""

# The avatar on sidebar
avatar: https://your-avatar-image-url.com  # Replace with your actual avatar URL

# Social preview image for SEO
social_preview_image: # optional

# Table of contents (TOC)
toc: true

comments:
  active: # Leave empty to disable or fill with a comments system like Disqus, Utterances, or Giscus.
  disqus:
    shortname: # Fill with Disqus shortname if using Disqus comments
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: title
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: pathname
    lang: en

pwa:
  enabled: true  # enable PWA feature (installable)
  cache:
    enabled: true  # enable PWA offline cache

paginate: 10

# Base URL of your site
baseurl: ""

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
